all:
	g++ src/soapNNallSingle.cpp -O3 -larmadillo -o allOne
	g++ src/soapNNall.cpp -O3 -larmadillo -o allTwo
	g++ src/scanLJ.cpp -O3 -larmadillo -o scanH
	g++ src/soapNNsurface.cpp -O3 -larmadillo -o surfaceTwo
	g++ src/soapNNsurfaceSingle.cpp -O3 -larmadillo -o surfaceOne
	g++ src/eliminateSurfaces.cpp -O3 -larmadillo -o elimSurf
	g++ src/soapNNHydrogen.cpp -O3 -larmadillo -o Hsoap
	g++ src/soapNNHydrogenSingle.cpp -O3 -larmadillo -o HsoapOne 
	g++ src/eliminateHs.cpp -O3 -larmadillo -o elimH
	g++ src/setUniqHydrogen.cpp -O3 -larmadillo -o putH
	g++ src/getEta1.cpp -O3 -larmadillo -o Eta1
	g++ src/getEta2.cpp -O3 -larmadillo -o Eta2
	g++ src/getEta3.cpp -O3 -larmadillo -o Eta3
	g++ src/getEta1One.cpp -O3 -larmadillo -o Eta1One
	g++ src/getEta2One.cpp -O3 -larmadillo -o Eta2One
	g++ src/getEta3One.cpp -O3 -larmadillo -o Eta3One 
	g++ -O3 src/soapNNsurfaceTriple.cpp -larmadillo -o surfaceThree
	g++ -O3 src/soapNNHydrogenTriple.cpp -larmadillo -o HsoapThree
	g++ -O3 src/getHydrogenCoverage.cpp -larmadillo -o HydrogenCoverage2
	g++ -O3 src/getHydrogenCoverage3.cpp -larmadillo -o HydrogenCoverage3
