#!/bin/sh


echo "How may I serve you today?\n\n\
    1 Scan Surface Hydrogen.\n\
    2 Get Eta1 Hs.\n\
    3 Get Eta2 Hs.\n\
    4 Get Eta3 Hs.\n\
    5 Get Soap Matrix on the Cluster Surface.\n\
    6 Get Soap Matrix on the Whole Cluster.\n\

    7 Get Soap Matrix of a Hydrogen Scan. Must do (1) before.\n\
    8 Get Unique Surface Atoms. Must do (2) before .\n\
    9 Get Unique Surface Hydrogens. Must do (4) before.\n\
    10 Set Hydrogen Atoms on Unique Surface Atom. Must do (5) before.\n\n"

read -p  ":  " a
q=1

  if [ $a -eq 1 ]; then
    ./scanHydrogen.sh
  fi
  if [ $a -eq 2 ]; then
    ./getEta1.sh
  fi
  if [ $a -eq 3 ]; then
    ./getEta2.sh
  fi
  if [ $a -eq 4 ]; then
    ./getEta3.sh
  fi

  if [ $a -eq 5 ]; then
    ./surface.sh 
  fi

  if [ $a -eq 6 ]; then
    ./allAt.sh 
  fi
  if [ $a -eq 7 ]; then
    ./soapHydrogen.sh 
  fi
  if [ $a -eq 8 ]; then
    ./elimSurface.sh 
  fi
  if [ $a -eq 9 ]; then
    ./elimHydrogen.sh 
  fi
  if [ $a -eq 10 ]; then
    ./putHydrogen.sh
  fi


